[default]
address="0.0.0.0"
port=8000
public_base_url="https://jt-morris.com"
auth0_domain="jt-morris.us.auth0.com"
auth0_client_id="oturdIbaS2pC6mhO0cXz2gSlVYdZFgwz"
auth0_audience="https://jt-morris.com"
auth0_client_secret="configure secret in environment variables!"
public_files_dir="./public"
support_email="support@jt-morris.com"
# database_url="postgresql://postgres:postgres@localhost:5432/postgres"
database_max_connections=22
template_dir="./templates/"
# aws_s3_endpoint=""

[default.webauthn]
relying_party_url="https://jt-morris.com"
relying_party_id="jt-morris.com"
relying_party_name="jt-morris.com"

[default.databases.primary]
url="postgresql://postgres:postgres@localhost:5432/postgres"
max_connections=22
connect_timeout=10


[test]
database_max_connections=1
public_base_url="https://test.jt-morris.com"

[test.tls]
certs="./tls/certificate"
key="./tls/key"


[default.tls]
certs="./tls/certificate"
key="./tls/key"
[release]
port=443

