name: Rust


on: [push]
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rs:
              - '**.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
  build:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    # if: needs.detect-changes.steps.changes.outputs.rs == 'true'
    env:
      "DIGITALOCEAN_ACCESS_TOKEN": ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      "ROCKET_AUTH0_CLIENT_SECRET": ${{secrets.AUTH0_CLIENT_SECRET}} 
      "ROCKET_DATABASE_URL": ${{secrets.ROCKET_DATABASE_URL}}
      "ROCKET_SECRET_KEY": ${{secrets.ROCKET_SECRET_KEY}}
    steps:
      - run: echo hello