[package]
name="game"
version="0.1.0"
edition="2021"

[target.'cfg(all(not(unix),target_os="windows"))'.dependencies]
windows={version="0.61",features=["Win32","Win32_Foundation","Win32_System_LibraryLoader","Win32_Graphics_Gdi","Win32_Graphics_OpenGL","Win32_UI","Win32_UI_WindowsAndMessaging"]}

[target.'cfg(unix)'.dependencies]
x11 = "2.21.0"

[dependencies]
gl = "0.14.0"
glutin = {version="0.32.3"}
glfw = "0.59.0"